export const FETCH_CAR_LIST = "FETCH_CAR_LIST"
export const DELETE_CAR = "DELETE_CAR"
export const ADD_NEW_CAR = "ADD_NEW_CAR"
export const UPDATE_CAR = "UPDATE_CAR"

export const FETCH_CAR_CATEGORY_LIST = "FETCH_CAR_CATEGORY_LIST"

export const FETCH_CUSTOMER_RECEIVE_ALERT_PRICE_LIST = "FETCH_CUSTOMER_RECEIVE_ALERT_PRICE_LIST"
export const ADD_NEW_CUSTOMER_RECEIVE_ALERT_PRICE_LIST = "ADD_NEW_CUSTOMER_RECEIVE_ALERT_PRICE_LIST"
export const DELETE_CUSTOMER_RECEIVE_ALERT_PRICE_LIST = "DELETE_CUSTOMER_RECEIVE_ALERT_PRICE_LIST"
export const UPDATE_CUSTOMER_RECEIVE_ALERT_PRICE_LIST = "UPDATE_CUSTOMER_RECEIVE_ALERT_PRICE_LIST"

export const FETCH_CUSTOMER_REGISTER_TEST_DRIVING = "FETCH_CUSTOMER_REGISTER_TEST_DRIVING"
export const ADD_NEW_CUSTOMER_REGISTER_TEST_DRIVING = "ADD_NEW_CUSTOMER_REGISTER_TEST_DRIVING"
export const DELETE_CUSTOMER_REGISTER_TEST_DRIVING = "DELETE_CUSTOMER_REGISTER_TEST_DRIVING"
export const UPDATE_CUSTOMER_REGISTER_TEST_DRIVING = "UPDATE_CUSTOMER_REGISTER_TEST_DRIVING"

